init_url  = "gemini://geminiprotocol.net/"
#init_url = "gemini://medusae.space"
#init_url = "gemini://datapulp.smol.pub/"

scroll_at = 6

[colors]
# black
background = [ 40,  40,  40]
# grey
border     = [128, 136, 144]
badlink    = [128, 136, 144]
# green
link       = [128, 255, 208]
# white
text       = [224, 240, 255]
list       = [224, 240, 255]
dialog     = [224, 240, 255]
banner     = [224, 240, 255]
# yellow
preformat  = [255, 208, 160]
quote      = [255, 208, 160]
# red
heading1   = [255, 144, 176]
heading2   = [255, 144, 176]
heading3   = [255, 144, 176]

[format]
margin      = 2
list_prefix = " - "
heading3    = [3, 2]
heading2    = [2, 1]
heading1    = [1, 0]

[keys]
global    = "g"
msg_view  = "m"
tab_view  = "t"
load_cfg  = "c"

[keys.tab]
move_up      = "o"
move_down    = "i"
move_left    = "e"
move_right   = "n"
cycle_left   = "E"
cycle_right  = "N"
inspect      = "w"
delete_tab   = "v"
new_tab      = "p"

[keys.dialog]
ack          = "y"
yes          = "y"
no           = "n"
