

init_url = "gemini://geminiprotocol.net/"

[gemcolors]
heading1  = [255, 128, 128]
heading2  = [255, 128, 128]
heading3  = [255, 128, 128]
text      = [205, 205, 205]
link      = [128, 205, 255]
quote     = [205, 205, 205]
listitem  = [205, 100, 205]
preformat = [100, 205, 100]
badlink   = [255,   1,   1]

[keys]
# yes/no dialog
yes                  = "y"
no                   = "n"
# navigation
move_cursor_up       = "o"
move_cursor_down     = "i"
move_page_up         = "g"
move_page_down       = "m"
cycle_to_left_tab    = "e"
cycle_to_right_tab   = "n"
inspect_under_cursor = "w"
delete_current_tab   = "v"
new_tab              = "p"
